"""Generate standalone C99 code for a discretized LLC plant model."""

from __future__ import annotations

from pathlib import Path
import re

from .discretize import DiscretePlant


def _identifier(name: str) -> str:
    cleaned = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "llc_" + cleaned
    return cleaned


def _format_array(values, suffix: str, precision: int) -> str:
    return ", ".join(f"{float(value):.{precision}e}{suffix}" for value in values)


def export_c99_plant_model(
    plant: DiscretePlant,
    directory: str | Path,
    *,
    basename: str = "llc_plant_model",
    use_float32: bool = True,
) -> dict[str, Path]:
    """Export a normalized direct-form difference equation as C99."""
    output = Path(directory)
    output.mkdir(parents=True, exist_ok=True)
    base = _identifier(basename)
    header_path = output / f"{base}.h"
    source_path = output / f"{base}.c"
    guard = f"{base.upper()}_H"
    ctype = "float" if use_float32 else "double"
    suffix = "f" if use_float32 else ""
    precision = 9 if use_float32 else 17
    denominator = plant.denominator
    numerator = plant.numerator
    y_history = max(len(denominator) - 1, 1)
    u_history = max(len(numerator) + plant.input_delay_samples, 1)

    header = f'''#ifndef {guard}
#define {guard}

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define {base.upper()}_Y_HISTORY {y_history}u
#define {base.upper()}_U_HISTORY {u_history}u

typedef struct {{
    {ctype} y_hist[{base.upper()}_Y_HISTORY];
    {ctype} u_hist[{base.upper()}_U_HISTORY];
}} {base}_t;

void {base}_init({base}_t *model);
{ctype} {base}_step({base}_t *model, {ctype} input_delta);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
'''
    source = f'''#include "{base}.h"

#include <string.h>

/*
 * LLC discrete plant model generated by power-design-toolkit.
 * Input:  delta {plant.input_name} [{plant.input_unit}]
 * Output: delta {plant.output_name} [{plant.output_unit}]
 * Ts:     {plant.sample_time_s:.17g} s
 * Method: exact zero-order hold, input delay={plant.input_delay_samples} samples
 *
 * Difference equation:
 * {plant.difference_equation.text(precision=9)}
 */

static const {ctype} k_den[{len(denominator)}] = {{
    {_format_array(denominator, suffix, precision)}
}};

static const {ctype} k_num[{len(numerator)}] = {{
    {_format_array(numerator, suffix, precision)}
}};

void {base}_init({base}_t *model)
{{
    if (model == NULL) {{
        return;
    }}
    (void)memset(model, 0, sizeof(*model));
}}

{ctype} {base}_step({base}_t *model, {ctype} input_delta)
{{
    size_t i;
    {ctype} output_delta = ({ctype})0;
    if (model == NULL) {{
        return ({ctype})0;
    }}

    for (i = {base.upper()}_U_HISTORY - 1u; i > 0u; --i) {{
        model->u_hist[i] = model->u_hist[i - 1u];
    }}
    model->u_hist[0] = input_delta;

    for (i = 1u; i < {len(denominator)}u; ++i) {{
        output_delta -= k_den[i] * model->y_hist[i - 1u];
    }}
    for (i = 0u; i < {len(numerator)}u; ++i) {{
        output_delta += k_num[i] * model->u_hist[i + {plant.input_delay_samples}u];
    }}

    for (i = {base.upper()}_Y_HISTORY - 1u; i > 0u; --i) {{
        model->y_hist[i] = model->y_hist[i - 1u];
    }}
    model->y_hist[0] = output_delta;
    return output_delta;
}}
'''
    header_path.write_text(header, encoding="utf-8")
    source_path.write_text(source, encoding="utf-8")
    return {"header": header_path, "source": source_path}


def export_c99_state_space_model(
    plant: DiscretePlant,
    directory: str | Path,
    *,
    basename: str = "llc_plant_state_space",
    use_float32: bool = True,
) -> dict[str, Path]:
    """Export the ZOH state-space realization, preferred for high-order use."""
    output = Path(directory)
    output.mkdir(parents=True, exist_ok=True)
    base = _identifier(basename)
    header_path = output / f"{base}.h"
    source_path = output / f"{base}.c"
    guard = f"{base.upper()}_H"
    ctype = "float" if use_float32 else "double"
    suffix = "f" if use_float32 else ""
    precision = 9 if use_float32 else 17
    n = plant.ad.shape[0]

    def matrix_rows(matrix) -> str:
        rows = []
        for row in matrix:
            rows.append("    { " + _format_array(row, suffix, precision) + " }")
        return ",\n".join(rows)

    header = f'''#ifndef {guard}
#define {guard}

#include <stddef.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define {base.upper()}_STATE_COUNT {n}u

typedef struct {{
    {ctype} x[{base.upper()}_STATE_COUNT];
}} {base}_t;

void {base}_init({base}_t *model);
{ctype} {base}_step({base}_t *model, {ctype} input_delta);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
'''
    source = f'''#include "{base}.h"

#include <string.h>

/* Exact ZOH state-space realization.
 * Input:  delta {plant.input_name} [{plant.input_unit}]
 * Output: delta {plant.output_name} [{plant.output_unit}]
 * Ts:     {plant.sample_time_s:.17g} s
 */

static const {ctype} k_ad[{n}][{n}] = {{
{matrix_rows(plant.ad)}
}};

static const {ctype} k_bd[{n}] = {{
    {_format_array(plant.bd[:, 0], suffix, precision)}
}};

static const {ctype} k_cd[{n}] = {{
    {_format_array(plant.cd[0, :], suffix, precision)}
}};

static const {ctype} k_dd = {float(plant.dd[0, 0]):.{precision}e}{suffix};

void {base}_init({base}_t *model)
{{
    if (model == NULL) {{
        return;
    }}
    (void)memset(model, 0, sizeof(*model));
}}

{ctype} {base}_step({base}_t *model, {ctype} input_delta)
{{
    size_t row;
    size_t col;
    {ctype} next[{n}];
    {ctype} output_delta = k_dd * input_delta;
    if (model == NULL) {{
        return ({ctype})0;
    }}
    for (row = 0u; row < {n}u; ++row) {{
        {ctype} value = k_bd[row] * input_delta;
        for (col = 0u; col < {n}u; ++col) {{
            value += k_ad[row][col] * model->x[col];
        }}
        next[row] = value;
        output_delta += k_cd[row] * model->x[row];
    }}
    for (row = 0u; row < {n}u; ++row) {{
        model->x[row] = next[row];
    }}
    return output_delta;
}}
'''
    header_path.write_text(header, encoding="utf-8")
    source_path.write_text(source, encoding="utf-8")
    return {"header": header_path, "source": source_path}
